// AUTO-GENERATED by generate_data.py from the real emolog SDK. Do not edit by hand.
window.EMOLOG_DATA = {
  "presets": [
    {
      "id": "sarcastic",
      "tag": "Flat \"I'm fine.\"",
      "transcript": "I'm fine.",
      "emotion": "angry",
      "confidence": 50,
      "arousal": "high",
      "valence": "negative",
      "contextString": "[Paralinguistic context: The user sounds angry (50% confidence). Speaking rate is moderate. Vocal energy is high. There is notable emphasis and stress in the delivery. ]",
      "convoMood": "Single turn",
      "convoDesc": "Not enough history yet for a conversational arc.",
      "tts": {
        "style": "calm and empathetic",
        "rate": "0.85",
        "stability": "0.25"
      },
      "baselineReply": "Great, glad to hear it! Is there anything else I can help you with today?",
      "awareReply": "I want to make sure this is actually resolved \u2014 you sound a little frustrated. Let's get it fixed properly."
    },
    {
      "id": "billing",
      "tag": "Angry, escalating",
      "transcript": "This is the THIRD time I've called about this.",
      "emotion": "angry",
      "confidence": 76,
      "arousal": "high",
      "valence": "negative",
      "contextString": "[Paralinguistic context: The user sounds angry (76% confidence). Speaking rate is fast. Vocal energy is very high. There is notable emphasis and stress in the delivery. ]\n\n[Conversation emotional arc: The user currently sounds angry (76% confidence). Overall conversation mood has been mixed. Overall energy level has been moderate. The user's mood appears to be worsening. The user's energy appears to be escalating. ALERT: Emotional state shifted from neutral to angry (worsened). Respond with empathy and de-escalation. Acknowledge the user's frustration before providing information. CAUTION: User appears increasingly distressed. Prioritize resolution and avoid lengthy explanations. ]",
      "convoMood": "Escalating \u2014 4 turns",
      "convoDesc": "Emotional state shifted from neutral to angry (worsened).",
      "tts": {
        "style": "calm and empathetic",
        "rate": "0.8",
        "stability": "0.2"
      },
      "baselineReply": "I understand, let me pull up your account. Can I get your account number please?",
      "awareReply": "I hear you \u2014 three calls for the same issue is genuinely frustrating. I'm escalating this right now so it gets fixed immediately."
    },
    {
      "id": "sad",
      "tag": "Quiet, drained",
      "transcript": "I don't really know what to do anymore.",
      "emotion": "sad",
      "confidence": 40,
      "arousal": "low",
      "valence": "negative",
      "contextString": "[Paralinguistic context: The user sounds sad (40% confidence). Speaking rate is very slow. Vocal energy is moderate. ]\n\n[Conversation emotional arc: The user currently sounds sad (40% confidence). Overall conversation mood has been negative. Overall energy level has been low-energy. Respond with warmth and patience. Avoid overly upbeat or transactional language. ]",
      "convoMood": "Stable \u2014 2 turns",
      "convoDesc": "Mood negative, low-energy. No sharp shift yet.",
      "tts": {
        "style": "warm and gentle",
        "rate": "0.85",
        "stability": "0.3"
      },
      "baselineReply": "Okay. Here's the information you requested. Let me know if you need anything else.",
      "awareReply": "Take your time \u2014 I'm here with you. Let's work through this together, one step at a time."
    },
    {
      "id": "happy",
      "tag": "Delighted",
      "transcript": "Oh my gosh, it arrived already?! That's amazing!",
      "emotion": "happy",
      "confidence": 50,
      "arousal": "high",
      "valence": "positive",
      "contextString": "[Paralinguistic context: The user sounds happy (50% confidence). Speaking rate is fast. Vocal energy is high. ]",
      "convoMood": "Single turn",
      "convoDesc": "Not enough history yet for a conversational arc.",
      "tts": {
        "style": "warm and engaged",
        "rate": "1.05",
        "stability": "0.4"
      },
      "baselineReply": "Your order has been marked as delivered. Please rate your experience below.",
      "awareReply": "That's so great to hear! Hope it's exactly what you wanted \u2014 let us know if anything needs a follow-up."
    },
    {
      "id": "neutral",
      "tag": "Just a question",
      "transcript": "Can you check my account balance?",
      "emotion": "neutral",
      "confidence": 45,
      "arousal": "low",
      "valence": "neutral",
      "contextString": "[Paralinguistic context: The user sounds neutral (45% confidence). Speaking rate is moderate. Vocal energy is moderate. ]",
      "convoMood": "Single turn",
      "convoDesc": "Not enough history yet for a conversational arc.",
      "tts": {
        "style": "natural",
        "rate": "1.0",
        "stability": "0.5"
      },
      "baselineReply": "Sure, one moment while I pull that up.",
      "awareReply": "Sure, one moment while I pull that up."
    }
  ],
  "benchmark": [
    {
      "name": "Empathy alignment",
      "baseline": 0.267,
      "emolog": 0.808
    },
    {
      "name": "Tone appropriateness",
      "baseline": 0.167,
      "emolog": 1.0
    },
    {
      "name": "Urgency calibration",
      "baseline": 0.867,
      "emolog": 0.967
    },
    {
      "name": "Emotion-context use",
      "baseline": 0.133,
      "emolog": 0.967
    }
  ],
  "meanLift": 0.502
};
